name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
      fail-fast: false  # Continue with other jobs even if one fails

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,test]"
    
    - name: Run tests with coverage
      run: |
        python -m pytest --cov=twsca --cov-report=xml tests/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run linters
      run: |
        python -m black --check .
        python -m isort --check-only .
        python -m flake8 --max-line-length=100 --ignore=E203,W503,E402,F401,F403,F405 --exclude=examples .
        python -m mypy --ignore-missing-imports .

#  docs:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.11'
#        cache: 'pip'
#    
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -e ".[docs]"
#    
#    - name: Build documentation
#      run: |
#        cd docs
#        make html 